[project]
name='aws-utils'
version='0.1'
dependencies = [
    #'Click',  # Will need to add this in once we setup command-line options
    'boto3',
    'urwid',
]
[project.scripts]
aws-ui = "aws_ui:main"
